[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://marco-technical-assessment.netlify.app/some-page"
  to = "https://www.google.com/search%3Fq%3Danything"
  status = 301
  force = true
